spring :
  datasource :
    url: jdbc:mysql://192.168.0.78:3306/testDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : studyuser
    password : 1111
    driver-class-name : com.mysql.cj.jdbc.Driver
    hikari : 
      maximum-pool-size : 10

  mvc :
    view : 
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    session:
      timeout: 1m

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.test.board.model